function! AirLineInit()
	let g:airline_section_a = airline#section#create([' ','mode'])
	let g:airline_section_b = airline#section#create_left(['ffenc','filetype'])
	"let g:airline_section_b = (['%{strftime("%c")}'])
	"let g:airline_section_y = (['BN: %{bufnr("%")}'])

	let g:airline_section_c = airline#section#create(['%f'])
	let g:airline_section_x = airline#section#create(['%P'])
	let g:airline_section_y = airline#section#create(['%B'])
	"let g:airline_section_z = airline#section#create_right(['%l','%c'])	
endfunction
autocmd VimEnter * call AirLineInit()

" -------- plugins -------- "
call plug#begin('~/.vim/plugged')

Plug 'ap/vim-css-color'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'sainnhe/gruvbox-material'

call plug#end()

" -------- airline config ------- "
let g:airline_theme='gruvbox_material'
let g:gruvbox_material_background = 'medium' " soft, medium, hard
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'unique_tail'

" function! AccentDemo()
"  let keys = ['Regalkun']
"  for k in keys
"    call airline#parts#define_text(k, k)
"  endfor
"  call airline#parts#define_accent('Regalkun', 'bold')
"  let g:airline_section_a = airline#section#create(keys)
"endfunction
"autocmd VimEnter * call AccentDemo()

  " powerline symbols "
  
	if !exists('g:airline_symbols')
    		let g:airline_symbols = {} " set airline custom  symbol
 	endif

  let g:airline_left_sep = ' '
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ' '
  let g:airline_right_alt_sep = ''
  let g:airline_symbols.branch = ''
  let g:airline_symbols.colnr = '   :'
  let g:airline_symbols.readonly = ''
  let g:airline_symbols.linenr = '   :'
  let g:airline_symbols.maxlinenr = '' 
  d
  
  let g:airline_symbols.dirty='⚡'

 " -------- key mapping -------- "
nnoremap <C-j> :tabprevious<CR>
nnoremap <C-k> :tabnext<CR>

" -------- other config -------- "
colorscheme gruvbox-material
set number
set termguicolors
syntax on
set mouse=a
"set t_Co=7
set background=dark " dark, light
set encoding=UTF-8
set guifont=JetBrainsMono\ Nerd\ Font\ 9
set laststatus=2


