#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & picom & dunst 
~/.config/polybar/launch.sh --material
~/.config/dunst/dunstrc
picom --experimental-backends &

bspc monitor -d I II III IV V VI VII VIII IX X

# Window Border Config
bspc config border_width          1
bspc config window_gap            3
bspc config top_padding		  1
bspc config left_padding	  1
bspc config right_padding 	  1
bspc config bottom_padding 	  1
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Window Border Colors
bspc config focused_border_color "#d1b6ad"
bspc config normal_border_color "#999497"
bspc config presel_feedback_color "#2A303D"

bspc config urgent_border_color "#D3304B"
bspc config focused_locked_border_color "#d1b6ad"
bspc config normal_sticky_border_color "#999497"
bspc config normal_locked_border_color "#999497"
bspc config focused_sticky_border_color "#d1b6ad"

# BSPWM Config
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Pictures/pic3.jpg
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
