#! /bin/sh

# ----------------  Autostart  -----------------

pgrep -x sxhkd > /dev/null || sxhkd & 
~/.config/polybar/launch.sh --shapes
xinput set-prop 12 282 1
# tint2 &
picom &
picom --experimental-backends &
xrdb -load ~/.Xdefaults &
dunst &
bspwm &
notify-send "Hello Regal.."

# -----------------  Monitor  ---------------------

bspc monitor -d I II III 

# ----------------  Window Border Config  -------------------

bspc config border_width          0
bspc config window_gap            4
bspc config top_padding		  1
bspc config left_padding	  5
bspc config right_padding 	  5
bspc config bottom_padding 	  5
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# ----------------  Window Border Colors  ---------------------

bspc config focused_border_color "#b8a198"
bspc config normal_border_color "#b8a198"

bspc config focused_locked_border_color "#b8a198"
bspc config normal_locked_border_color "#b8a198"

# ------------------  Another BSPWM Config  -----------------------

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Pictures/pic1.jpg
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
