#! /bin/sh

#					
#
#		██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#		██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#		██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#		██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#		██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#		╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#					       
#
#
#  =========================================================================
#


# ----------------  Autostart  -----------------

pgrep -x sxhkd > /dev/null || sxhkd & 
~/.config/polybar/fin/launch.sh
picom &
# tint2 &
xrdb -load ~/.Xdefaults &
dunst &
bspwm &
notify-send "Hello Regal.." "Glad to see u" -i ~/.icons/gradient/person.png

# -----------------  Monitor  ---------------------

bspc monitor -d I II III 

# ----------------  Window Border Config  -------------------

bspc config border_width          3
bspc config window_gap            5   
bspc config top_padding		  0
bspc config left_padding	  5
bspc config right_padding 	  5
bspc config bottom_padding 	  8
bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true

# ----------------  Window Border Colors  ---------------------

bspc config focused_border_color "#bf616a"
bspc config normal_border_color "#a3be8c"

bspc config focused_locked_border_color "#bf616a"
bspc config normal_locked_border_color "#a3be8c"

# ------------------  Another BSPWM Config  -----------------------

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Pictures/key.jpg
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
