#! /bin/sh

#					
#
#		██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#		██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#		██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#		██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#		██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#		╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#					       
#
#
#  =========================================================================
#

# ----------------  Autostart  -----------------

pgrep -x sxhkd > /dev/null || sxhkd &
xinput set-prop 13 303 1
~/.config/polybar/launch.sh --shapes
# wal -R -a 90
# tint2 &
picom --experimental-backends &
xrdb -load ~/.Xdefaults &
dunst &
bspwm &
notify-send "Hello Regal.." "Glad to see u" -i ~/.icons/gradient/person.png

# -----------------  Monitor  ---------------------

bspc monitor -d I II III 

# ----------------  Window Border Config  -------------------

bspc config border_width          0
bspc config window_gap            5   
bspc config top_padding		  22
bspc config left_padding	  22
bspc config right_padding 	  22
bspc config bottom_padding 	  25
bspc config split_ratio           1.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true

# ----------------  Window Border Colors  ---------------------

bspc config focused_border_color "#6C6E6E"
bspc config normal_border_color "#5E6162"

bspc config focused_locked_border_color "#6C6E6E"
bspc config normal_locked_border_color "#5E6162"

# ------------------  Another BSPWM Config  -----------------------

bspc rule -a Gimp desktop=state=floating follow=on
bspc rule -a Chromium desktop=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill $HOME/Pictures/posture.jpg
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true
